import type { Metadata } from "next";
import "./globals.css";
import PrimaryNav from "@/components/layout/PrimaryNav";

export const metadata: Metadata = {
  title: "Gather The Geeks",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body className={`antialiased`}
    >

        <PrimaryNav/>
        <main className={"px-2 md:px-24 py-8"}>
            {children}
        </main>


    </body>
    </html>
  );
}
